### ISSUE TITLE
二维码扫不出来

### ISSUE THREAD

**Issue by czl0325** [nanchen2251/AiYaScanner#3]
![image](https://user-images.githubusercontent.com/2100549/52022800-705abd00-2535-11e9-811c-e6235e3d5448.png)

**Comment by nanchen2251** [comment]
这个二维码有毒，我试了QQ、微信都可以扫，后面再研究一下。

**Comment by czl0325** [comment]
感谢，研究出来告诉我一下。

**Comment by ailiwean** [comment]
大哥， 这种模糊类型的码 zxing，zbar应该扫不出的， 微信他们底层都是自己写的。  你要搞出来了， 你就成大牛了

**Comment by appdev** [comment]
@nanchen2251 @czl0325 https://github.com/simplepeng/wechat-scanner 试试这个 微信的扫码，我试了一下，秒出结果

**Comment by czl0325** [comment]
> @nanchen2251 @czl0325 https://github.com/simplepeng/wechat-scanner 试试这个 微信的扫码，我试了一下，秒出结果

感谢你了！！！！
